apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubenode-depl
spec:
  replicas: 5
  selector:
    matchLabels:
      app: kubenode
  template:
    metadata:
      labels:
        app: kubenode
    spec:
      containers:
        - name: kubenode
          image: soumyadeepdutta/kubenode:latest
---
apiVersion: v1
kind: Service
metadata:
  name: kubenode-clusterip-srv
spec:
  selector:
    app: kubenode
  ports:
    - name: kubenode
      protocol: TCP
      port: 80
      targetPort: 4000
  type: NodePort